# Generated by Django 2.1.1 on 2018-10-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twwebdesign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('message', models.CharField(blank=True, max_length=900)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
